// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vote_API.Dal;

#nullable disable

namespace Vote_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Vote_API.Models.Dto.PlaylistVoteDto", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SpotifyPlaylistSongUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Uuid");

                    b.ToTable("PlaylistVoteDto");
                });

            modelBuilder.Entity("Vote_API.Models.Dto.SpotifyPlaylistSongDto", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ArtistName")
                        .HasColumnType("longtext");

                    b.Property<string>("SongImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("SongName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SpotifyPlaylistUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Uuid");

                    b.HasIndex("SpotifyPlaylistUuid");

                    b.ToTable("SpotifyPlaylistSongDto");
                });

            modelBuilder.Entity("Vote_API.Models.Dto.VoteablePlaylistDto", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("PlaylistImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("PlaylistName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("VoteDataUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Uuid");

                    b.HasIndex("VoteDataUuid");

                    b.ToTable("VoteablePlaylistDto");
                });

            modelBuilder.Entity("Vote_API.Models.Dto.VoteDataDto", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorUserUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Uuid");

                    b.ToTable("VoteData");
                });

            modelBuilder.Entity("Vote_API.Models.Dto.SpotifyPlaylistSongDto", b =>
                {
                    b.HasOne("Vote_API.Models.Dto.VoteablePlaylistDto", null)
                        .WithMany("SongsInPlaylist")
                        .HasForeignKey("SpotifyPlaylistUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vote_API.Models.Dto.VoteablePlaylistDto", b =>
                {
                    b.HasOne("Vote_API.Models.Dto.VoteDataDto", null)
                        .WithMany("VoteablePlaylistCollection")
                        .HasForeignKey("VoteDataUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vote_API.Models.Dto.VoteablePlaylistDto", b =>
                {
                    b.Navigation("SongsInPlaylist");
                });

            modelBuilder.Entity("Vote_API.Models.Dto.VoteDataDto", b =>
                {
                    b.Navigation("VoteablePlaylistCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
