name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore Docker-api-s.sln
      - name: Build
        run: dotnet build Docker-api-s.sln --no-restore
      - name: Test
        run: dotnet test Docker-api-s.sln --no-build --verbosity normal
