name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore Docker-api-s.sln
      - name: Build
        run: dotnet build Docker-api-s.sln --no-restore
      - name: Start dependencies (docker-compose)
        run: |
          docker-compose up -d
      - name: Wait for Mariadb Server container
        uses: jakejarvis/wait-action@master
        with:
          time: "5s"
      - name: Show containers
        run: docker container ls
      - name: Test
        run: dotnet test Docker-api-s.sln --no-build --verbosity normal
